services:
  - type: web
    name: fraud-link-detection-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
  - type: web
    name: fraud-link-detection-ml
    env: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true